export enum EActionType {
  SIGNIN = 'SIGNIN',
  SIGNOUT = 'SIGNOUT',
  SET_USER = 'SET_USER',
  SET_CUSTOMER = 'SET_CUSTOMER',
  SET_LOADING = 'SET_LOADING',
  SET_PERMISSIONS = 'SET_PERMISSIONS',
  SET_CUSTOMERS = 'SET_CUSTOMERS',
}
